= A comparison of Java frameworks

This repo contains a microbenchmark that collects the compile time, startup time, memory usage, and load time of
simple "Hello World"-like apps in Spring, Quarkus, Micronaut, and Helidon.

As always, you should do your own experimentation using samples that represent your real application.

== Background
This is an adaptation of Matthias Graf's link:https://medium.com/better-programming/which-java-microservice-framework-should-you-choose-in-2020-4e306a478e58[original work].

This original work led to responses from the project maintainers, worth a view!

- link: https://www.youtube.com/watch?v=rJFgdFIs_k8[Micronaut]
- link: https://quarkus.io/blog/io-thread-benchmark/[Quarkus]


== Running
Make sure you do all of the Prerequisites first!

To run the microbenchmark, execute the script in this repo link:compare/measure.sh[measure.sh]
[source,shell]
----
cd <path-to-this-repo>/compare
./measure.sh
----

== Prerequisites
=== DataStax Astra

1. Create a free-forever Cassandra Database with DataStax Astra. Use the keyspace name `ks1` and the username/password combo `datastax/datastax` when creating the db to make things easy.  link:https://astra.datastax.com/register?utm_source=github&utm_medium=referral&utm_campaign=java-framework-compare[click here to get started] 🚀
2. Download the Secure Connect Bundle from the UI to your machine. link: https://docs.astra.datastax.com/docs/obtaining-database-credentials[docs]
3. Set the ENV variable `ASTRA_DB_BUNDLE` to the location of the secure connect bundle on your machine.
[source,shell]
----
export ASTRA_DB_BUNDLE=<path-to-your-secure-connect-db.zip>
----

=== Apache JMeter

Install the link:https://jmeter.apache.org/[jmeter] tool and make it available via global `jmeter` command on your machine.

This repo is using `jmeter` for load-testing, i.e: `jmeter -n -t loadtest.jmx -j jmeter.out -l jmeter.log`
To see more info on how to install JMeter, visit the link:https://jmeter.apache.org/usermanual/get-started.html#install[installation guide].

If you are on Mac OSX you can leverage the brew tool:
[source,shell]
----
brew install jmeter
----

=== Java

Install Java JDK (at least 1.8)

=== Docker

Install Docker: it is used to run the all microservices in this project:

* Check link:https://docs.docker.com/install/[the installation guide],
and link:https://docs.docker.com/docker-for-mac/install/[the MacOS installation guide];
* If you just installed docker, be sure that your current user can run a container (no root
required). On Linux, check
link:https://docs.docker.com/install/linux/linux-postinstall/[the post-installation guide].

=== GraalVM
If you want to run and collect measurements for quarkus-graal project, you need to have GraalVM installed:

* Install link:https://quarkus.io/guides/building-native-image[GraalVM];
* Install platform C developer tools:
    ** Linux:
        *** Make sure header files are installed on your system.
            **** On Fedora `sudo dnf install zlib-devel`;
            **** Otherwise `sudo apt-get install libz-dev`;
    ** macOS:
        *** `xcode-select --install`;
* Set `GRAALVM_HOME` to your GraalVM Home directory e.g. `/opt/graalvm` on Linux or
  `/path/to/GraalVM/Contents/Home` on macOS;
